version: '3.9'

services:
  db:
    image: postgres:16.2
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5123:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  api:
    build: ./FamTreeApi
    ports:
      - 8081:8080
    depends_on:
      - db
volumes:
  pgdata:
